### ISSUE TITLE
error running python citation.py

### ISSUE THREAD

**Issue by joyce04** [gear/gfnn#3]
I wasn't able to run experiments following instructions on READMe.
When I run `python citation.py --no-cuda --model gfnn --dataset cora`, 
the first error pops up is following : 
```
File "citation.py", line 7, in <module>
    from utils import load_citation, sgc_precompute, set_seed, stack_feat
ImportError: cannot import name 'load_citation' from 'utils' (/Users/grace/Downloads/gfnn-36667861caacba921469d43917d002896e832c3f/gfnn-36667861caacba921469d43917d002896e832c3f/utils.py)
```

If I run after converting load_citation function from comments to codes, I face another issue :

```
File "citation.py", line 11, in <module>
    from args import get_citation_args
ImportError: cannot import name 'get_citation_args' from 'args' (/Users/grace/Downloads/gfnn-36667861caacba921469d43917d002896e832c3f/gfnn-36667861caacba921469d43917d002896e832c3f/args.py)
```

However, the `get_citation_args` function is nowhere to be found. Is there another way to run gfnn with cora dataset?

**Comment by gear** [comment]
Hi, sorry for the mess because I was doing a refactoring sometime ago... 
Could you checkout to commit `bd7b3c869dd6e05c470b3c058bee277c4cb7d530`? It should run fine there.
For example: `python citation.py --model gfnn`.

**Comment by joyce04** [comment]
Thanks! it works fine now!

**Comment by uestc-lese** [comment]
> Hi, sorry for the mess because I was doing a refactoring sometime ago... Could you checkout to commit `bd7b3c869dd6e05c470b3c058bee277c4cb7d530`? It should run fine there. For example: `python citation.py --model gfnn`.

bd7b3c869dd6e05c470b3c058bee277c4cb7d530  Is it a magnetic link?
